### ISSUE TITLE
Add necessary hooks to link PRs, Issues and users in documentation

### ISSUE THREAD

**Issue by RondeauG** [hydrologie/xhydro#15]
### Addressing a Problem?

Links following the format `(:pull:number)` are used throughout a few files such as `HISTORY.rst` to link to previous PRs, Issues, and Users. However, the proper `sphinx` hooks need to be implemented for them to work.

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by Zeitsperre** [comment]
Sounds good. There are a few things I can add to the cookiecutter to enable this functionality. I think it's totally worth it.

**Comment by Zeitsperre** [comment]
Related: #14

**Comment by Zeitsperre** [comment]
This is merged (#14), but because we place the history in the metadata sent to PyPI, this is causing an error. We need to remove this info, unfortunately. Will address tomorrow.
