### ISSUE TITLE
Importations xscen

### ISSUE THREAD

**Issue by RondeauG** [hydrologie/xhydro#19]
### Addressing a Problem?

`xscen` possède déjà plusieurs fonctionnalités qui pourraient être réutilisées directement dans `xhydro`, notamment pour le calcul d'indicateurs (excluant les indicateurs fréquentiels plus avancés) et pour les fonctions nécessaires aux analyses hydroclimatiques (`climatological_mean`, `compute_deltas`, `ensemble_stats`, `generate_weights`, `produce_horizon`).

### Potential Solution

Plutôt que de copier-coller le code, je propose d'importer les fonctions `xscen` pertinentes et de les passer au `__init__`, ce qui signifie qu'on peut par exemple directement utiliser `xhydro.ensemble_stats`, sans avoir à se soucier du fait que le code se trouve dans une autre librairie. Il existe également la mécanique pour transposer la documentation vers le ReadTheDocs.

### Additional context

J'ai créé une branche, pour que vous puissiez voir à quoi ça pourrait ressembler: https://github.com/hydrologie/xhydro/tree/indicators/xhydro 

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by Zeitsperre** [comment]
One thing worth noting (I'm going to sound like a broken record to @RondeauG) is that if we make `xscen` an installation dependency, this will pull in all the dependencies that xscen depends upon. From the scope of `xhydro`, it's very possible that there's going to be a fair amount of overlap, but it's worth considering as well.

For creating the bridge between `xhydro` and `xscen`, the documentation for the `intersphinx` plugin can be found here: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
