### ISSUE TITLE
value n'affiche pas ce qu'il faut pour les indicateurs

### ISSUE THREAD

**Issue by TC-FF** [hydrologie/xhydro#40]
### Setup Information

- xhydro version: 0.2
- Python version:
- Operating System:

### Description

J'extrait une station (j'ai testé 023422 et 090605), je calcul un indicateur (j'ai testé min et max) et les valeurs affichées par 
ds_4fa.streamflow_min_annual et ds_4fa.streamflow_min_annual.values sont différentes

### Steps To Reproduce

```
ds = xd.Query(
    **{
        "datasets":{
            "deh":{
                "id" :["023422"],
                "variables":["streamflow"],'spatial_agg':['watershed']
            }
        },

  }
).data.squeeze().load()

ds["id"].attrs["cf_role"] = "timeseries_id"
ds["streamflow"].attrs = {"long_name": "Streamflow", "units": "m3 s-1", "standard_name": "water_volume_transport_in_river_channel", "cell_methods": "time: mean"}

ds_4fa = xh.indicators.get_yearly_op(ds, op="min", missing="pct", missing_options={"tolerance": 0.15})

ds_4fa.streamflow_min_annual

ds_4fa.streamflow_min_annual.values
```

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by RondeauG** [comment]
Mmh... Je viens de tester de mon côté avec la console python et tout fonctionne correctement. Idem si j'applique `dropna(dim="time")`.

J'ai donc plutôt l'impression que c'est ton setup qui cause le problème. Est-ce que ça te donne la même chose quand tu essaies de faire ça directement sur `ds.streamflow` ?

**Comment by TC-FF** [comment]
Je viens de refaire le test, même chose dans vscode :
![image](https://github.com/hydrologie/xhydro/assets/110991420/99ac31c7-71f9-4569-a4b7-20a5b65353ab)
Mais quand je roule le code dans Jupyter, plus de problèmes... C'est bizarre... 
![image](https://github.com/hydrologie/xhydro/assets/110991420/3b1ff288-df79-41e4-8486-a81f9b0de858)
Je ferme le issue, qui n'est visiblement pas en lien avec xhydro
