### ISSUE TITLE
Pydantic update is breaking xscen and xhydro

### ISSUE THREAD

**Issue by sebastienlanglois** [hydrologie/xhydro#64]
### Setup Information

- xhydro version: 0.3.0
- Python version: 3.9 to 3.11
- Operating System: Ubuntu

### Description

Pydantic have just made a new release today (2023-12-22) and since then, we are getting errors coming from xscen : 
![image](https://github.com/hydrologie/xhydro/assets/42305216/aee91447-5a24-44b9-961c-f27ac7a4a50f)

### Steps To Reproduce

Installing xscen or xhydro in a new environment with pydantic's newest release (v2.5.3).

### Additional context

@Zeitsperre 
@RondeauG 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by Zeitsperre** [comment]
Temporary fixes have been proposed in #61 and #62.

**Comment by sebastienlanglois** [comment]
I'm closing for now as we have a temporary fix.
